version: '2'
services:
  db:
    image: mongo
    volumes:
      - ./db_data:/data/db
      - .:/code
    ports:
      - "27017:27017"
  web:
    build: .
    command: python -u app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/code
      - ../people-counting-opencv:/code/people-counting-opencv
    depends_on:
      - db
